---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::r-immunedeconv=2.1.2
  - bioconda::bioconductor-annotationdbi=1.72.0
  - bioconda::bioconductor-org.hs.eg.db=3.22.0
  - bioconda::bioconductor-org.mm.eg.db=3.22.0