---
title: "Difference Abundance Report"
subtitle: "aggiungere sottotitolo"
author:
  - name: Bioinfo TEAM 
    url: https://github.com/NEGEDIA
    affiliation: NEGEDIA
    affiliation-url: http://www.ngdx.eu/
---

## Analisi {{< var project >}}

La pagina html viene generata utilizzando il Quarto e, per ora, utilzziamo il formato html per avere un singolo file in cui sono elencati tutti i risultati.
In alto c'è la barra con titolo e sottotitolo, quello che farei è:
- aggiungere il logo
- aggiungere un tema 
- ...

Per creare questo file html sono necessari diversi file, solo per la sua creazione. Questi non saranno necessari per visualizzare in seguito l'html.
In ordine:
- _quarto.yml
- _variables.yml
- style.css

## Section

Ciao

### subsection 1

### subsection 2


## _quarto.yml
In qesto file sono presenti tutte le impostazioni utili a generare il file html. Ad esempio: la presenza o meno del TOC e la sua posizione, che tipo di file voglio in output, le varie informazioni, il tema e la posizione del file style.css

## _variables.yml
In questo file sono incluse le variabili che faranno riferimento ai file generati durante la pipeline. Sarò comodo includerli in questo modo e poi utilizzarli come file var con la sintassi {{< var >}}. Un esempio è il nome del progetto, che cambia in base alla variabile project che inserisco nel file yml.

## style.css
::: justify
Il file css è il file che permette di includere guide, impostazioni, temi ed altro al file html. Ad esempio questo chunk utilizza la formattazione **giustificato**, settato nel file css.
:::

