name: "propr_propr"
description: |
  Perform logratio-based correlation analysis -> get proportionality & basis shrinkage partial correlation coefficients.
  One can also compute standard correlation coefficients, if required.
keywords:
  - coexpression
  - correlation
  - proportionality
  - logratio
  - propr
  - corpcor

tools:
  - "propr":
      description: "Logratio methods for omics data"
      homepage: "https://github.com/tpq/propr"
      documentation: "https://rdrr.io/cran/propr/man/propr.html"
      tool_dev_url: "https://github.com/tpq/propr"
      doi: "10.1038/s41598-017-16520-0"
      licence: ["GPL-2"]
  - "corpcor":
      description: "Efficient Estimation of Covariance and (Partial) Correlation"
      homepage: "https://cran.r-project.org/web/packages/corpcor/index.html"
      documentation: "https://cran.r-project.org/web/packages/corpcor/corpcor.pdf"
      doi: "10.2202/1544-6115.1175"
      licence: ["GPL >=3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information.
        This can be used at the workflow level to pass optional parameters to the module.
        [id: 'test', ...]
  - count:
      type: file
      description: |
        Count matrix, where rows = variables or genes, columns = samples or cells.
        This matrix should not contain zeros. Otherwise, they will be replaced by the minimun number.
        It is recommended to handle the zeros beforehand with the method of preference.
      pattern: "*.{csv,tsv}"
  - transformation:
      type: string
      description: |
        (Optional) 'clr' or 'alr'. If null, then do not transform the data. Default: 'clr'
  - reference:
      type: string
      description: |
        (Optional) Reference gene for ALR transformation. It can be a number refering to the gene index or a string corresponding to the gene name.
        Default = last variable
  - alpha:
      type: float
      description: |
        (Optional) Alpha parameter for Box-Cox transformation. Default = null, standard log transformation is applied to the ratios.
  - metric:
      type: string
      description: |
        Correlation metric to use.
        To compute proportionality, options are 'rho', 'phi', 'phs'.
        To compute partial correlation with basis shrinkage, use 'pcor.bshrink'.
        To compute logratio variance, use 'vlr'.
        Default = pcor.bshrink
      pattern: "*.{csv,tsv}"
  - permutation:
      type: integer
      description: |
        (Optional) Number of permutation cycles to calculate FDR. Default = 0, no permutation.
  - cutoff_min:
      type: float
      description: |
        (Optional) Minimun FDR cutoff to test.
  - cutoff_max:
      type: float
      description: |
        (Optional) Maximun FDR cutoff to test.
  - cutoff_interval:
      type: float
      description: |
        (Optional) Step between each cutoff.

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information.
        This can be used at the workflow level to pass optional parameters to the module.
        [id: 'test', ...]
  - matrix:
      type: file
      description: Coefficient matrix
      pattern: "*.propr.tsv"
  - fdr:
      type: file
      description: (optional) propr fdr table
      pattern: "*.fdr.tsv"
  - session_info:
      type: file
      description: dump of R SessionInfo
      pattern: "*.R_sessionInfo.log"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@suzannejin"
